version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: crm_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - crm-net

  backend:
    build:
      context: ./backend
    container_name: crm_backend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=8888
      - DATABASE=mongodb://mongo:27017/fluxia
      - JWT_SECRET=supersecretjwt
    depends_on:
      - mongo
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - crm-net

  frontend:
    build:
      context: ./frontend
    container_name: crm_frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "--port", "3000"]
    networks:
      - crm-net

volumes:
  mongo_data:
  backend_node_modules:
  frontend_node_modules:

networks:
  crm-net:
    driver: bridge